
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ian
 */
public class tutFrame extends javax.swing.JFrame {

    /**
     * Creates new form tutFrame
     */
    public tutFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ImageIcon notimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("notsymbol.png")));
        Image notimg1 = notimg.getImage();
        Image notimg2 = notimg1.getScaledInstance(jnotlab.getWidth(), jnotlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(notimg2);
        jnotlab.setIcon(i);
        
        ImageIcon andimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("andsymbol.png")));
        Image andimg1 = andimg.getImage();
        Image andimg2 = andimg1.getScaledInstance(jandlab.getWidth() , jandlab.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon i1 = new ImageIcon(andimg2);
        jandlab.setIcon(i1);
        
        ImageIcon orimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("orsymbol.png")));
        Image orimg1 = orimg.getImage();
        Image orimg2 = orimg1.getScaledInstance(jorlab.getWidth(), jorlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i2 = new ImageIcon(orimg2);
        jorlab.setIcon(i2);
        
        ImageIcon nandimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("nandsymbol.png")));
        Image nandimg1 = nandimg.getImage();
        Image nandimg2 = nandimg1.getScaledInstance(jnandlab.getWidth(), jnandlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i3 = new ImageIcon(nandimg2);
        jnandlab.setIcon(i3);
        
        ImageIcon norimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("norsymbol.png")));
        Image norimg1 = norimg.getImage();
        Image norimg2 = norimg1.getScaledInstance(jnorlab.getWidth(), jnorlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i4 = new ImageIcon(norimg2);
        jnorlab.setIcon(i4);
        
        ImageIcon posimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("possymbol.jpg")));
        Image posimg1 = posimg.getImage();
        Image posimg2 = posimg1.getScaledInstance(jposlab.getWidth(), jposlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i5 = new ImageIcon(posimg2);
        jposlab.setIcon(i5);
        
        ImageIcon sopimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("sopsymbol.jpg")));
        Image sopimg1 = sopimg.getImage();
        Image sopimg2 = sopimg1.getScaledInstance(jsoplab.getWidth(), jsoplab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i6 = new ImageIcon(sopimg2);
        jsoplab.setIcon(i6);
        
        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icong.png")));
        Image icon1 = icon.getImage();
        Image icon2 = icon1.getScaledInstance(jiconlab.getWidth(), jiconlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iconimg = new ImageIcon(icon2);
        jiconlab.setIcon(iconimg);
        
        ImageIcon xorimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("xorsymbol.png")));
        Image xorimg1 = xorimg.getImage();
        Image xorimg2 = xorimg1.getScaledInstance(jxorlab.getWidth(), jxorlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i7 = new ImageIcon(xorimg2);
        jxorlab.setIcon(i7);
        
        ImageIcon xnorimg = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("xnorsymbol.png")));
        Image xnorimg1 = xnorimg.getImage();
        Image xnorimg2 = xnorimg1.getScaledInstance(jxnorlab.getWidth(), jxnorlab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i8 = new ImageIcon(xnorimg2);
        jxnorlab.setIcon(i8);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jiconlab = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jbtnand = new javax.swing.JButton();
        jandlab = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jbtnnot = new javax.swing.JButton();
        jnotlab = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jbtnor = new javax.swing.JButton();
        jorlab = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jbtnnand = new javax.swing.JButton();
        jnandlab = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jbtnnor = new javax.swing.JButton();
        jnorlab = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jbtnpos = new javax.swing.JButton();
        jposlab = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jbtnsop = new javax.swing.JButton();
        jsoplab = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jbtnxor = new javax.swing.JButton();
        jxorlab = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jbtnxnor = new javax.swing.JButton();
        jxnorlab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("LOGIC_CIRCUIT_EDUCATIONAL_GAME");

        jiconlab.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jiconlabMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jiconlab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jiconlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 0));

        jLabel6.setBackground(new java.awt.Color(255, 204, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setText("RIAL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TUTO");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });

        jbtnand.setBackground(new java.awt.Color(255, 204, 0));
        jbtnand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnand.setText("AND gate");
        jbtnand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnandMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnandMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnandMousePressed(evt);
            }
        });
        jbtnand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jandlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnand, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jandlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jbtnand))
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });

        jbtnnot.setBackground(new java.awt.Color(255, 204, 0));
        jbtnnot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnnot.setText("NOT gate");
        jbtnnot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnnotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnnotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnnotMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnnotMousePressed(evt);
            }
        });
        jbtnnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnnot, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jnotlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jnotlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnnot))
        );

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });

        jbtnor.setBackground(new java.awt.Color(255, 204, 0));
        jbtnor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnor.setText("OR gate");
        jbtnor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnorMousePressed(evt);
            }
        });
        jbtnor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jorlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnor, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jorlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jbtnor))
        );

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });

        jbtnnand.setBackground(new java.awt.Color(255, 204, 0));
        jbtnnand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnnand.setText("NAND gate");
        jbtnnand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnnandMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnnandMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnnandMousePressed(evt);
            }
        });
        jbtnnand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jnandlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnnand, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jnandlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jbtnnand))
        );

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel15MouseExited(evt);
            }
        });

        jbtnnor.setBackground(new java.awt.Color(255, 204, 0));
        jbtnnor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnnor.setText("NOR gate");
        jbtnnor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnnorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnnorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnnorMousePressed(evt);
            }
        });
        jbtnnor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnnor, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jnorlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jnorlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jbtnnor))
        );

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel16MouseExited(evt);
            }
        });

        jbtnpos.setBackground(new java.awt.Color(255, 204, 0));
        jbtnpos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnpos.setText("Product of sums");
        jbtnpos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnposMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnposMousePressed(evt);
            }
        });
        jbtnpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnpos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jposlab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jposlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnpos))
        );

        jPanel17.setBackground(new java.awt.Color(153, 153, 153));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel17MouseExited(evt);
            }
        });

        jbtnsop.setBackground(new java.awt.Color(255, 204, 0));
        jbtnsop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnsop.setText("Sum of products");
        jbtnsop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnsopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnsopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnsopMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnsopMousePressed(evt);
            }
        });
        jbtnsop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnsop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jsoplab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsoplab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jbtnsop))
        );

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel18MouseExited(evt);
            }
        });

        jbtnxor.setBackground(new java.awt.Color(255, 204, 0));
        jbtnxor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnxor.setText("XOR gate");
        jbtnxor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnxorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnxorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnxorMousePressed(evt);
            }
        });
        jbtnxor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnxor, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jxorlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jxorlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jbtnxor))
        );

        jPanel19.setBackground(new java.awt.Color(153, 153, 153));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel19MouseExited(evt);
            }
        });

        jbtnxnor.setBackground(new java.awt.Color(255, 204, 0));
        jbtnxnor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnxnor.setText("XNOR gate");
        jbtnxnor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnxnorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnxnorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnxnorMousePressed(evt);
            }
        });
        jbtnxnor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxnorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnxnor, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jxnorlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jxnorlab, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jbtnxnor))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int op = JOptionPane.showConfirmDialog(null , "Are you sure you want to exit?" , "EXIT" , JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if(op == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        indexFrame inPage = new indexFrame();
        inPage.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setForeground(Color.red);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setForeground(Color.black);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Color.YELLOW);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButton1MouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        jPanel9.setBackground(Color.red);
        
        
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        jPanel9.setBackground(Color.GRAY);
        
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        jPanel8.setBackground(Color.red);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        jPanel8.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        jPanel10.setBackground(Color.RED);
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        jPanel10.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel11.setBackground(Color.red);
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        jPanel11.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseEntered
        jPanel15.setBackground(Color.red);
    }//GEN-LAST:event_jPanel15MouseEntered

    private void jPanel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseExited
        jPanel15.setBackground(Color.GRAY);
    }//GEN-LAST:event_jPanel15MouseExited

    private void jPanel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseEntered
        jPanel18.setBackground(Color.red);
    }//GEN-LAST:event_jPanel18MouseEntered

    private void jPanel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseExited
        jPanel18.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel18MouseExited

    private void jPanel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseEntered
        jPanel19.setBackground(Color.red);
    }//GEN-LAST:event_jPanel19MouseEntered

    private void jPanel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseExited
        jPanel19.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel19MouseExited

    private void jPanel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseEntered
        jPanel17.setBackground(Color.red);
    }//GEN-LAST:event_jPanel17MouseEntered

    private void jPanel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseExited
        jPanel17.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel17MouseExited

    private void jPanel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseEntered
        jPanel16.setBackground(Color.red);
    }//GEN-LAST:event_jPanel16MouseEntered

    private void jPanel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseExited
        jPanel16.setBackground(Color.gray);
    }//GEN-LAST:event_jPanel16MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        jButton1.setForeground(Color.red);
    }//GEN-LAST:event_jButton1MousePressed

    private void jbtnnotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnotMouseEntered
        jbtnnot.setForeground(Color.red);
    }//GEN-LAST:event_jbtnnotMouseEntered

    private void jbtnnotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnotMouseExited
        jbtnnot.setForeground(Color.black);
    }//GEN-LAST:event_jbtnnotMouseExited

    private void jbtnandMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnandMouseEntered
        jbtnand.setForeground(Color.RED);
    }//GEN-LAST:event_jbtnandMouseEntered

    private void jbtnandMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnandMouseExited
        jbtnand.setForeground(Color.black);
    }//GEN-LAST:event_jbtnandMouseExited

    private void jbtnorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnorMouseEntered
        jbtnor.setForeground(Color.red);
    }//GEN-LAST:event_jbtnorMouseEntered

    private void jbtnorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnorMouseExited
        jbtnor.setForeground(Color.black);
    }//GEN-LAST:event_jbtnorMouseExited

    private void jbtnnandMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnandMouseEntered
        jbtnnand.setForeground(Color.red);
    }//GEN-LAST:event_jbtnnandMouseEntered

    private void jbtnnandMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnandMouseExited
        jbtnnand.setForeground(Color.black);
    }//GEN-LAST:event_jbtnnandMouseExited

    private void jbtnnorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnorMouseEntered
        jbtnnor.setForeground(Color.red);
    }//GEN-LAST:event_jbtnnorMouseEntered

    private void jbtnnorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnorMouseExited
        jbtnnor.setForeground(Color.black);
    }//GEN-LAST:event_jbtnnorMouseExited

    private void jbtnxorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnxorMouseEntered
        jbtnxor.setForeground(Color.red);
    }//GEN-LAST:event_jbtnxorMouseEntered

    private void jbtnxorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnxorMouseExited
        jbtnxor.setForeground(Color.BLACK);
    }//GEN-LAST:event_jbtnxorMouseExited

    private void jbtnxnorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnxnorMouseEntered
        jbtnxnor.setForeground(Color.red);
    }//GEN-LAST:event_jbtnxnorMouseEntered

    private void jbtnxnorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnxnorMouseExited
        jbtnxnor.setForeground(Color.black);
    }//GEN-LAST:event_jbtnxnorMouseExited

    private void jbtnsopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnsopMouseEntered
        jbtnsop.setForeground(Color.red);
    }//GEN-LAST:event_jbtnsopMouseEntered

    private void jbtnsopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnsopMouseExited
        jbtnsop.setForeground(Color.black);
    }//GEN-LAST:event_jbtnsopMouseExited

    private void jbtnposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnposMouseEntered
        jbtnpos.setForeground(Color.red);
    }//GEN-LAST:event_jbtnposMouseEntered

    private void jbtnposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnposMouseExited
        jbtnpos.setForeground(Color.black);
    }//GEN-LAST:event_jbtnposMouseExited

    private void jbtnnotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnotMouseClicked
       jbtnnot.setForeground(Color.green);
    }//GEN-LAST:event_jbtnnotMouseClicked

    private void jbtnnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnotActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(true);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnnotActionPerformed

    private void jbtnnotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnotMousePressed
        jbtnnot.setForeground(Color.green);
    }//GEN-LAST:event_jbtnnotMousePressed

    private void jbtnandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnandActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(true);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnandActionPerformed

    private void jbtnandMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnandMousePressed
        jbtnand.setForeground(Color.green);
    }//GEN-LAST:event_jbtnandMousePressed

    private void jbtnorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnorMousePressed
        jbtnor.setForeground(Color.green);
    }//GEN-LAST:event_jbtnorMousePressed

    private void jbtnorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnorActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(true);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnorActionPerformed

    private void jbtnnandMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnandMousePressed
        jbtnnand.setForeground(Color.green);
    }//GEN-LAST:event_jbtnnandMousePressed

    private void jbtnnandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnandActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(true);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnnandActionPerformed

    private void jbtnnorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnnorMousePressed
        jbtnnor.setForeground(Color.green);
    }//GEN-LAST:event_jbtnnorMousePressed

    private void jbtnnorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnorActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(true);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnnorActionPerformed

    private void jbtnxorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnxorMousePressed
        jbtnxor.setForeground(Color.green);
    }//GEN-LAST:event_jbtnxorMousePressed

    private void jbtnxorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxorActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(true);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnxorActionPerformed

    private void jbtnxnorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnxnorMousePressed
        jbtnxnor.setForeground(Color.GREEN);
    }//GEN-LAST:event_jbtnxnorMousePressed

    private void jbtnxnorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxnorActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(true);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnxnorActionPerformed

    private void jiconlabMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jiconlabMouseDragged
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        
        this.setLocation(X , Y);
    }//GEN-LAST:event_jiconlabMouseDragged

    private void jbtnsopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnsopMouseClicked

    }//GEN-LAST:event_jbtnsopMouseClicked

    private void jbtnsopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsopActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(true);
        gfobj.posPanel.setVisible(false);
        this.hide();
    }//GEN-LAST:event_jbtnsopActionPerformed

    private void jbtnsopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnsopMousePressed
        jbtnsop.setForeground(Color.GREEN);
    }//GEN-LAST:event_jbtnsopMousePressed

    private void jbtnposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnposActionPerformed
        gateFrame gfobj = new gateFrame();
        
        gfobj.setVisible(true);
        gfobj.notPanel.setVisible(false);
        gfobj.andPanel.setVisible(false);
        gfobj.orPanel.setVisible(false);
        gfobj.nandPanel.setVisible(false);
        gfobj.norPanel.setVisible(false);
        gfobj.xorPanel.setVisible(false);
        gfobj.xnorPanel.setVisible(false);
        gfobj.sopPanel.setVisible(false);
        gfobj.posPanel.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_jbtnposActionPerformed

    private void jbtnposMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnposMousePressed
        jbtnpos.setForeground(Color.GREEN);
    }//GEN-LAST:event_jbtnposMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tutFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jandlab;
    private javax.swing.JButton jbtnand;
    private javax.swing.JButton jbtnnand;
    private javax.swing.JButton jbtnnor;
    private javax.swing.JButton jbtnnot;
    private javax.swing.JButton jbtnor;
    private javax.swing.JButton jbtnpos;
    private javax.swing.JButton jbtnsop;
    private javax.swing.JButton jbtnxnor;
    private javax.swing.JButton jbtnxor;
    private javax.swing.JLabel jiconlab;
    private javax.swing.JLabel jnandlab;
    private javax.swing.JLabel jnorlab;
    private javax.swing.JLabel jnotlab;
    private javax.swing.JLabel jorlab;
    private javax.swing.JLabel jposlab;
    private javax.swing.JLabel jsoplab;
    private javax.swing.JLabel jxnorlab;
    private javax.swing.JLabel jxorlab;
    // End of variables declaration//GEN-END:variables
}
